/**
* Creating a sidebar enables you to:
- create an ordered group of docs
- render a sidebar for each doc of that group
- provide next/previous navigation

The sidebars can be generated from the filesystem, or explicitly defined here.

Create as many sidebars as you want.
*/

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  guidesSidebar: [
    { 
      type: 'html',
      className: 'sidebar-title',
      value: (() => {
        switch (process.env.DOCUSAURUS_CURRENT_LOCALE) {
          default: return "News";
        }
      })(),
      defaultStyle: true,
    },
    {
      type: 'link',
      href: '/cs2update',
      label: 'CS2 Server News',
    },
    {
      type: 'html',
      className: 'sidebar-title',
      value: (() => {
        switch (process.env.DOCUSAURUS_CURRENT_LOCALE) {
          default: return "First steps";
        }
      })(),
      defaultStyle: true,
    },
    "welcome",
    {
      type: 'category',
      label: 'Account',
      items: [
        "banned",
        "account-paymentoptions",
      ]
    },
    "faq",
    "free-vs-pro",
    "firststeps-locations",
    "network/network-analysis",
    {
      type: 'category',
      label: 'Pro Control Panel',
      items: [
        "dashboard",
        "serverlist",
        "editserver"
      ]
    },
    {
      type: 'category',
      label: 'Support',
      items: [
        "contactsupport",
        "create-screenshots"
      ]
    },
  ],

  //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  gameserverSidebar: [
    {
      type: 'html',
      className: 'sidebar-title',
      value: (() => {
        switch (process.env.DOCUSAURUS_CURRENT_LOCALE) {
          default: return "First steps";
        }
      })(),
      defaultStyle: true,
    },
    "server-faqs",
    "server-rcon",
    {  
      type: 'html',
      className: 'sidebar-title',
      value: (() => {
        switch (process.env.DOCUSAURUS_CURRENT_LOCALE) {
          default: return "Popular Games";
        }
      })(),
      defaultStyle: false,
    },
    {
      type: "category",
      label: "Counter-Strike 2",
      link: {
        type: 'doc',
        id: 'cs2/index',
      },
      items: [
        "cs2/cs2-becomeadmin",
        "cs2/cs2-firststeps-dashboard",
        "cs2/cs2-cstv",
        "cs2/source-gsltoken",
        "cs2/plugins/cs2-plugins-ingamecommands",
        "cs2/cs2-pluginslist",
        "cs2/cs2-rcon",
        {
          type: "category",
          label: "CS2 Pro Plugins",
          items: [
            "cs2/plugins/cs2-plugins-cstvdiscord",
            "cs2/plugins/cs2-plugins-simpleadmin",
            "cs2/plugins/cs2-plugins-matchzy",
            "cs2/plugins/cs2-plugins-openprefireprac",
            "cs2/plugins/cs2-plugins-retakes",
            "cs2/plugins/cs2-plugins-skins",
          ]
        },
      ],
    },
    {
      type: 'html',
      className: 'sidebar-title',
      value: (() => {
        switch (process.env.DOCUSAURUS_CURRENT_LOCALE) {
          default: return "All Games (A-Z)";
        }
      })(),
      defaultStyle: false,
    },
    {
      type: "category",
      label: "Call of Duty",
      link: {
        type: 'doc',
        id: 'cod/index',
      },
      items: [
        "cod/cod-firststeps-dashboard",
        "cod/cod-rcon"
      ],
    },
    {
      type: "category",
      label: "Call of Duty 2",
      link: {
        type: 'doc',
        id: 'cod2/index',
      },
      items: [
        "cod2/cod2-firststeps-dashboard",
        "cod2/cod2-rcon"
      ],
    },
    {
      type: "category",
      label: "Call of Duty 4: Modern Warfare",
      link: {
        type: 'doc',
        id: 'cod4/index',
      },
      items: [
        "cod4/cod4-landing",
        "cod4/cod4-rcon",
        {
          type: "category",
          label: "Mods",
          items: [
            "cod4/mods/cod4-mods-promodlive",
            "cod4/mods/cod4-mods-fpspromod",
            "cod4/mods/cod4-mods-gungame",
            "cod4/mods/cod4-mods-codjumper",
            "cod4/mods/cod4-mods-stock-custom-maps"
          ]
        },
        "cod4/cod4-customfeatures"
      ],
    },
    {
      type: "category",
      label: "Call of Duty: United Offensive",
      link: {
        type: 'doc',
        id: 'coduo/index',
      },
      items: [
        "coduo/coduo-firststeps-dashboard",
        "coduo/coduo-rcon"
      ],
    },
    {
      type: "category",
      label: "Counter-Strike 1.6",
      link: {
        type: 'doc',
        id: 'cs16/index',
      },
      items: [
        "cs16/cs16-firststeps-dashboard",
        "cs16/cs16-becomeadmin",
        "cs16/cs16-rcon"
      ],
    },
    {
      type: "category",
      label: "Counter-Strike Condition Zero",
      link: {
        type: 'doc',
        id: 'cscz/index',
      },
      items: [
        "cscz/cscz-firststeps-dashboard",
        "cscz/cscz-becomeadmin",
        "cscz/cscz-rcon"
      ],
    },
    {
      type: "category",
      label: "Counter-Strike Source",
      link: {
        type: 'doc',
        id: 'css/index',
      },
      items: [
        "css/css-firststeps-dashboard",
        "css/css-rcon"
      ],
    },
    {
      type: "category",
      label: "Half-Life 1: Deathmatch",
      link: {
        type: 'doc',
        id: 'hldm/index',
      },
      items: [
        "hldm/hldm-firststeps-dashboard",
        "hldm/hldm-rcon"
      ],
    },
    {
      type: "category",
      label: "Minecraft",
      link: {
        type: 'doc',
        id: 'minecraft/index',
      },
      items: [
        "minecraft/minecraft-firststeps-dashboard",
        "minecraft/minecraft-rcon",
        "minecraft/minecraft-join"
      ],
    },
    {
      type: "category",
      label: "Medal of Honor: Allied Assault",
      link: {
        type: 'doc',
        id: 'mohaa/index',
      },
      items: [
        "mohaa/moha-dashboard",
        "mohaa/rcon"
      ],
    },
  ]
};

export default sidebars;
