name: deploy-docusaurus

on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-docusaurus:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          path: 'docusaurus'
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}        
      # Node is required for npm
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 19       
      # Install and build the Docusaurus website
      - name: Install & Build Docusaurus 
        run: |
          npm install --save @docusaurus/plugin-pwa
          npm install --save @docusaurus/plugin-client-redirects
          npm install --save docusaurus-lunr-search
          npm install --save prism-react-renderer
          npm install 
          npm run build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: /
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
